[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow = "HzqA6VnYkhSFtBUdwELU6M87Grst1gGLx6zu5aDe1vak"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
